version: '3.8'

services:
  auth-db:
    image: postgres:latest
    container_name: auth-db
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data

  team-db:
    image: postgres:latest
    container_name: team-db
    environment:
      POSTGRES_DB: team
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - team-db-data:/var/lib/postgresql/data

volumes:
  auth-db-data:
  team-db-data:
